### ISSUE TITLE
Is Pretrained Delta Checkpoint REQUIRED for Inference?

### ISSUE THREAD

**Issue by LaxmanSinghTomar** [XPixelGroup/DepictQA#1]
Hello Team,

Thanks for releasing the code.

In the models' section, it is mentioned that pre-trained delta model is not required for inference. 

![CleanShot 2024-06-13 at 17 26 40@2x](https://github.com/XPixelGroup/DepictQA/assets/37807897/ad48bd6a-826a-4026-9e56-bc7f145cf724)

However, in `gradio demo` as well as `inference` section, it is highlighted that this model must be downloaded and referred in `config.yaml`.

![CleanShot 2024-06-13 at 17 27 24@2x](https://github.com/XPixelGroup/DepictQA/assets/37807897/17f99511-1981-48a7-880e-c6319803134e)

Can you clarify if this is an essential requirement for `inference` or `demo`? What is the significance of this checkpoint?

**Comment by zhiyuanyou** [comment]
The delta checkpoint is required for **both inference and demo**. It is not required for training. 

We will release the delta checkpoint in this week.

**Comment by zhiyuanyou** [comment]
Also, thanks for pointing out the ambiguity in README.  We have updated the README. 

The delta checkpoint is actually **the parameters of lora and vision projector**, which means **the trainable parameters**.

**Comment by LaxmanSinghTomar** [comment]
Thanks, looking forward to it.

**Comment by zhiyuanyou** [comment]
Hello, the weights are available. 

More weights and the whole dataset are coming soon.
