### ISSUE TITLE
CUDA OOM Error & image size can not be too large

### ISSUE THREAD

**Issue by zhiyuanyou** [XPixelGroup/DepictQA#10]
In A6000 48G GPU, when image size is larger than 300+, causing CUDA out of memory error.

**Comment by pooregg** [comment]
意思是图像宽，高像素都不能超过300pix ?

**Comment by zhiyuanyou** [comment]
这是我自己提的issue，用于与开发的commit相关联。在这个issue下面，你会看到"[zhiyuanyou](https://github.com/zhiyuanyou) closed this as [completed](https://github.com/XPixelGroup/DepictQA/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/XPixelGroup/DepictQA/commit/53b8b7eee092b0bfbfe5de33c76812a3c0abf050 on Aug 9"这一句话。这意味着，resolution不能太大这个问题，已经在这一commit ( https://github.com/XPixelGroup/DepictQA/commit/53b8b7eee092b0bfbfe5de33c76812a3c0abf050 ) 解决了。具体的解决方案是加入了vision abstractor。目前，模型可以支持1000+的图像。
