### ISSUE TITLE
Stuck during inference

### ISSUE THREAD

**Issue by zhiyuanyou** [XPixelGroup/DepictQA#4]
A small proportion of samples (around 0.1%) suffer from stuck for batch inference. This is because the padding operation in batch inference. Two ways to solve:
1. Set batch size = 1. 
2. Do not mask padding tokens if batch size is larger than 1.

**Comment by jl1914** [comment]
Hi, I'm interested in the reasons why padding causes inference to get stuck. Could you elaborate on the details?

https://github.com/XPixelGroup/DepictQA/blob/ae4b38ccdc64d153a15c89d9c81f7e3b22fe934f/src/model/depictqa.py#L433

**Comment by zhiyuanyou** [comment]
Hello,


I think the main reason is the gap bwtween training and inference.&nbsp;


During training, to maintain the original resolution of images from different datasets, batch size is set as 1. So, there is no padding.&nbsp;


However, during inference, if batch size is larger than 1, there is the padding.&nbsp;

---Original---
From: ***@***.***&gt;
Date: Tue, Dec 10, 2024 19:34 PM
To: ***@***.***&gt;;
Cc: "You ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [XPixelGroup/DepictQA] Stuck during inference (Issue #4)




 
Hi, I'm interested in the reasons why padding causes inference to get stuck. Could you elaborate on the details?
