### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by Zdxfgre** [XPixelGroup/DepictQA#6]
Hello，thank for you code release. Does the provided training script perform LoRA fine-tuning or full parameter training after execution?

**Comment by zhiyuanyou** [comment]
Hello, thanks for your interests. The provided training scripts perform LoRA fine-tuning.

**Comment by Zdxfgre** [comment]
> Hello, thanks for your interests. The provided training scripts perform LoRA fine-tuning.

ok, I get it, thank you
